name: Deploy Piwigo to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Extract Piwigo
        id: download_piwigo
        run: |
          PIWIGO_VERSION="14.0.0" 
          PIWIGO_URL="https://piwigo.org/download/dlcounter.php?code=latest&id=piwigo-${PIWIGO_VERSION}.zip"

          # Install unzip on the runner
          sudo apt-get update && sudo apt-get install unzip -y

          curl -L "${PIWIGO_URL}" -o piwigo.zip
          unzip piwigo.zip -d piwigo-temp
          mkdir -p piwigo/
          mv piwigo-temp/piwigo/* piwigo/
          rm -rf piwigo-temp piwigo.zip

      - name: Upload Piwigo files to VPS using SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "piwigo/"
          target: "/storage/"

      - name: Execute Setup and Configuration Script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # --- START VPS SETUP SCRIPT ---

            # Use php8 as the package prefix (e.g., php8-fpm)
            PHP_MAJOR_VERSION="8"
            PHP_PREFIX="php\${PHP_MAJOR_VERSION}"
            # Define the actual service name expected by OpenRC (e.g., php-fpm8)
            PHP_FPM_SERVICE="php-fpm\${PHP_MAJOR_VERSION}"

            # 1. Update and install necessary packages 
            apk update
            apk add --no-cache nginx \
              \${PHP_PREFIX}-fpm \
              \${PHP_PREFIX}-mysqli \
              \${PHP_PREFIX}-pdo_mysql \
              \${PHP_PREFIX}-exif \
              \${PHP_PREFIX}-gd \
              \${PHP_PREFIX}-curl \
              \${PHP_PREFIX}-json \
              \${PHP_PREFIX}-session \
              \${PHP_PREFIX}-zlib \
              \${PHP_PREFIX}-iconv \
              \${PHP_PREFIX}-dom \
              mariadb-client \
              imagemagick

            # 2. Configure PHP-FPM
            # Configuration file path (e.g., /etc/php8/php-fpm.d/www.conf)
            WWW_CONF="/etc/\${PHP_PREFIX}/php-fpm.d/www.conf"

            # Ensure listen.owner/group are set for Nginx to access the socket
            sed -i 's/^;listen.owner/listen.owner/' \${WWW_CONF}
            sed -i 's/^;listen.group/listen.group/' \${WWW_CONF}

            # 3. Configure Nginx with IPv6 (::) and domain
            cat << 'EOL' > /etc/nginx/http.d/piwigo.conf
            server {
                listen [::]:80;
                server_name insidepumpkin.com; 
                root /storage/piwigo;
                index index.php index.html index.htm;

                location / {
                    try_files \$uri \$uri/ /index.php?\$args;
                }

                location ~ \.php$ {
                    try_files \$uri =404;
                    fastcgi_split_path_info ^(.+\.php)(/.+)\$;
                    # The default socket path for php-fpm is /run/php-fpm.sock, regardless of versioned service name
                    fastcgi_pass unix:/run/php-fpm.sock; 
                    fastcgi_index index.php;
                    include fastcgi.conf;
                    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                }
            }
            EOL

            # 4. Permissions
            chown -R nginx:nginx /storage/piwigo

            # 5. Enable and Start Services using OpenRC
            # CRITICAL FIX: Use the versioned service name (e.g., php-fpm8) for OpenRC
            rc-update add \${PHP_FPM_SERVICE} default 
            rc-update add nginx default

            rc-service \${PHP_FPM_SERVICE} start
            rc-service nginx start

            echo "Deployment and basic web server setup complete."

            # --- END VPS SETUP SCRIPT ---
