name: Deploy Piwigo to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Extract Piwigo
        run: |
          PIWIGO_VERSION="14.0.0"
          PIWIGO_URL="https://piwigo.org/download/dlcounter.php?code=latest&id=piwigo-${PIWIGO_VERSION}.zip"

          sudo apt-get update && sudo apt-get install unzip -y

          curl -L "${PIWIGO_URL}" -o piwigo.zip
          unzip piwigo.zip -d piwigo-temp
          mkdir -p piwigo/
          mv piwigo-temp/piwigo/* piwigo/
          rm -rf piwigo-temp piwigo.zip

      - name: Upload Piwigo files to VPS using SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "piwigo/"
          target: "/storage/"

      - name: Execute Setup and Configuration Script on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # --- START VPS SETUP SCRIPT ---

            PHP_VERSION="81"
            PHP_PREFIX="php${PHP_VERSION}"
            PHP_FPM_SERVICE="php-fpm${PHP_VERSION}"

            apk update
            apk add --no-cache nginx \
              ${PHP_PREFIX}-fpm \
              ${PHP_PREFIX}-mysqli \
              ${PHP_PREFIX}-pdo_mysql \
              ${PHP_PREFIX}-exif \
              ${PHP_PREFIX}-gd \
              ${PHP_PREFIX}-curl \
              ${PHP_PREFIX}-session \
              ${PHP_PREFIX}-iconv \
              ${PHP_PREFIX}-dom \
              ${PHP_PREFIX}-fileinfo \
              ${PHP_PREFIX}-zip \
              ${PHP_PREFIX}-mbstring \
              mariadb-client \
              imagemagick

            # --- PHP-FPM config (TCP mode) ---
            WWW_CONF="/etc/${PHP_PREFIX}/php-fpm.d/www.conf"
            sed -i 's|^listen = .*|listen = 127.0.0.1:9000|' ${WWW_CONF}

            # --- Nginx config ---
            cat << 'EOL' > /etc/nginx/http.d/piwigo.conf
            server {
                listen [::]:80;
                server_name insidepumpkin.com;
                root /storage/piwigo;
                index index.php index.html index.htm;

                location / {
                    try_files $uri $uri/ /index.php?$args;
                }

                location ~ \.php$ {
                    try_files $uri =404;
                    fastcgi_split_path_info ^(.+\.php)(/.+)$;
                    fastcgi_pass 127.0.0.1:9000;
                    fastcgi_index index.php;
                    include fastcgi.conf;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                }
            }
            EOL

            # --- Permissions ---
            chown -R nginx:nginx /storage/piwigo

            # --- Services ---
            rc-update add ${PHP_FPM_SERVICE} default
            rc-update add nginx default
            rc-service ${PHP_FPM_SERVICE} restart || rc-service ${PHP_FPM_SERVICE} start
            rc-service nginx restart || rc-service nginx start

            # --- MariaDB Setup ---
            mysql -h "${{ secrets.VPS_MYSQL_HOST }}" -u root -p"${{ secrets.VPS_MYSQL_PASSWORD }}" <<SQL
            CREATE DATABASE IF NOT EXISTS \`${{ secrets.VPS_MYSQL_DATABASE }}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
            CREATE USER IF NOT EXISTS '${{ secrets.VPS_MYSQL_USER }}'@'%' IDENTIFIED BY '${{ secrets.VPS_MYSQL_PASSWORD }}';
            GRANT ALL PRIVILEGES ON \`${{ secrets.VPS_MYSQL_DATABASE }}\`.* TO '${{ secrets.VPS_MYSQL_USER }}'@'%';
            FLUSH PRIVILEGES;
            SQL

            echo "Deployment complete. Nginx + PHP-FPM (TCP mode) + MariaDB ready."
            # --- END VPS SETUP SCRIPT ---
